/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kompetensum_keepsafe_Crypto */

#ifndef _Included_com_kompetensum_keepsafe_Crypto
#define _Included_com_kompetensum_keepsafe_Crypto
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kompetensum_keepsafe_Crypto
 * Method:    PBKDF2WithHmacSHA1
 * Signature: ([B[BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_kompetensum_keepsafe_Crypto_PBKDF2WithHmacSHA1
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
