/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kompetensum_keepsafe_Crypto */

#ifndef _Included_com_kompetensum_keepsafe_Crypto
#define _Included_com_kompetensum_keepsafe_Crypto
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kompetensum_keepsafe_Crypto
 * Method:    PBKDF2WithHmacSHA1
 * Signature: ([B[BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_kompetensum_keepsafe_Crypto_PBKDF2WithHmacSHA1
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_kompetensum_keepsafe_Crypto
 * Method:    AES256CBCPKCS5Padding_Encrypt
 * Signature: ([B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_kompetensum_keepsafe_Crypto_AES256CBCPKCS5Padding_1Encrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_kompetensum_keepsafe_Crypto
 * Method:    AES256CBCPKCS5Padding_Decrypt
 * Signature: ([B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_kompetensum_keepsafe_Crypto_AES256CBCPKCS5Padding_1Decrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_kompetensum_keepsafe_Crypto
 * Method:    GenerateRandom
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_kompetensum_keepsafe_Crypto_GenerateRandom
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
