/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kompetensum_keepsafe_NativeCrypto */

#ifndef _Included_com_kompetensum_keepsafe_NativeCrypto
#define _Included_com_kompetensum_keepsafe_NativeCrypto
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kompetensum_keepsafe_NativeCrypto
 * Method:    PBKDF2WithHmacSHA1
 * Signature: ([B[BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_kompetensum_keepsafe_NativeCrypto_PBKDF2WithHmacSHA1
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_kompetensum_keepsafe_NativeCrypto
 * Method:    AES256CBCPKCS5Padding_Encrypt
 * Signature: ([B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_kompetensum_keepsafe_NativeCrypto_AES256CBCPKCS5Padding_1Encrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_kompetensum_keepsafe_NativeCrypto
 * Method:    AES256CBCPKCS5Padding_Decrypt
 * Signature: ([B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_kompetensum_keepsafe_NativeCrypto_AES256CBCPKCS5Padding_1Decrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_kompetensum_keepsafe_NativeCrypto
 * Method:    GenerateRandom
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_kompetensum_keepsafe_NativeCrypto_GenerateRandom
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_kompetensum_keepsafe_NativeCrypto
 * Method:    AllInOneDecrypt
 * Signature: ([B[BI[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_kompetensum_keepsafe_NativeCrypto_AllInOneDecrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jbyteArray, jbyteArray);

/*
 * Class:     com_kompetensum_keepsafe_NativeCrypto
 * Method:    AllInOneEncrypt
 * Signature: ([B[B[BIJ[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_kompetensum_keepsafe_NativeCrypto_AllInOneEncrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jint, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
